console.log("customer 1  request")
console.log("deliverd to customer")
console.log("customer 2  request")
console.log("deliverd to customer")
console.log("customer 3  request")
console.log("deliverd to customer")